# Markov pattern

In [1]:
import copy
import numpy as np
def get_attack_list(graph_num,frame_num):
    attack_list = []
    transition_matrix_list = [[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2],[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2]]
    for frame in range(frame_num):
        attack_list_frame = []
        for group in range(graph_num):
            attack_list_frame.append(1)
        attack_list.append(attack_list_frame)
    p_q = [0.25,0.25,0.25,0.25]    
    
    for frame in range(frame_num):
        if frame == 0:
            p0 = np.array(p_q)
        else : 
            p0 = np.array(transition_matrix_list[index])
        index = np.random.choice([0,1,2,3], p = p0.ravel())
        print(frame,index)
        attack_list_copy = copy.copy(attack_list) #?
        attack_list_copy[frame][index] = 0
    return attack_list_copy

attack_list_copy = get_attack_list(4,4000)
# print(attack_list)
filename = 'markov_attack_list_0713_2022_1.txt'
np.savetxt(filename,attack_list_copy)
print(attack_list_copy)

0 1
1 2
2 0
3 3
4 0
5 2
6 2
7 0
8 0
9 3
10 0
11 3
12 3
13 2
14 2
15 0
16 3
17 1
18 2
19 3
20 0
21 0
22 3
23 2
24 2
25 3
26 2
27 3
28 0
29 2
30 2
31 1
32 1
33 3
34 0
35 2
36 2
37 0
38 0
39 0
40 0
41 2
42 0
43 2
44 3
45 2
46 2
47 1
48 3
49 2
50 0
51 2
52 3
53 0
54 2
55 0
56 0
57 0
58 2
59 1
60 2
61 3
62 0
63 0
64 2
65 0
66 2
67 2
68 2
69 2
70 0
71 2
72 0
73 2
74 0
75 0
76 2
77 0
78 0
79 0
80 2
81 0
82 2
83 0
84 2
85 3
86 2
87 0
88 0
89 2
90 1
91 2
92 0
93 2
94 0
95 2
96 3
97 3
98 0
99 2
100 2
101 0
102 1
103 2
104 0
105 0
106 2
107 0
108 2
109 2
110 0
111 2
112 3
113 3
114 2
115 1
116 0
117 2
118 2
119 0
120 3
121 0
122 0
123 0
124 1
125 2
126 0
127 3
128 1
129 3
130 0
131 2
132 3
133 2
134 0
135 2
136 0
137 1
138 2
139 0
140 0
141 2
142 3
143 2
144 0
145 0
146 0
147 0
148 2
149 0
150 0
151 2
152 0
153 0
154 1
155 0
156 0
157 3
158 2
159 0
160 3
161 1
162 1
163 2
164 3
165 1
166 3
167 1
168 2
169 0
170 0
171 3
172 1
173 1
174 2
175 0
176 2
177 2
178 3
179 3
180 0
181 0
182 1
183 0
184 1


2491 2
2492 3
2493 1
2494 2
2495 0
2496 3
2497 2
2498 3
2499 2
2500 0
2501 0
2502 2
2503 2
2504 0
2505 2
2506 0
2507 2
2508 1
2509 2
2510 0
2511 2
2512 2
2513 0
2514 0
2515 3
2516 2
2517 1
2518 3
2519 2
2520 2
2521 0
2522 2
2523 1
2524 0
2525 0
2526 0
2527 2
2528 2
2529 1
2530 3
2531 1
2532 0
2533 2
2534 3
2535 0
2536 0
2537 0
2538 0
2539 1
2540 1
2541 3
2542 3
2543 1
2544 3
2545 0
2546 0
2547 2
2548 1
2549 0
2550 2
2551 0
2552 2
2553 0
2554 2
2555 0
2556 0
2557 2
2558 2
2559 0
2560 2
2561 0
2562 1
2563 0
2564 2
2565 0
2566 2
2567 1
2568 2
2569 0
2570 0
2571 2
2572 0
2573 2
2574 3
2575 0
2576 2
2577 3
2578 0
2579 1
2580 2
2581 2
2582 2
2583 2
2584 1
2585 0
2586 2
2587 0
2588 2
2589 2
2590 3
2591 1
2592 1
2593 3
2594 1
2595 3
2596 2
2597 0
2598 2
2599 0
2600 2
2601 2
2602 0
2603 0
2604 2
2605 0
2606 2
2607 0
2608 2
2609 0
2610 0
2611 1
2612 3
2613 2
2614 2
2615 2
2616 1
2617 1
2618 0
2619 2
2620 2
2621 2
2622 0
2623 0
2624 2
2625 0
2626 3
2627 2
2628 0
2629 2
2630 3
2631 0
2632 3
2633 2

3740 2
3741 0
3742 2
3743 1
3744 1
3745 3
3746 2
3747 0
3748 0
3749 1
3750 1
3751 0
3752 3
3753 1
3754 0
3755 2
3756 0
3757 2
3758 1
3759 0
3760 2
3761 1
3762 3
3763 2
3764 0
3765 1
3766 2
3767 0
3768 3
3769 2
3770 3
3771 2
3772 3
3773 1
3774 0
3775 2
3776 2
3777 2
3778 0
3779 1
3780 2
3781 0
3782 3
3783 3
3784 0
3785 3
3786 2
3787 2
3788 0
3789 1
3790 1
3791 1
3792 3
3793 3
3794 3
3795 1
3796 1
3797 2
3798 0
3799 1
3800 0
3801 0
3802 2
3803 2
3804 2
3805 1
3806 0
3807 0
3808 2
3809 3
3810 1
3811 2
3812 0
3813 0
3814 2
3815 0
3816 2
3817 1
3818 0
3819 0
3820 2
3821 1
3822 0
3823 0
3824 2
3825 2
3826 0
3827 1
3828 2
3829 0
3830 0
3831 0
3832 3
3833 0
3834 1
3835 2
3836 1
3837 2
3838 1
3839 3
3840 2
3841 0
3842 2
3843 1
3844 2
3845 1
3846 1
3847 0
3848 2
3849 0
3850 0
3851 3
3852 3
3853 0
3854 1
3855 0
3856 0
3857 0
3858 2
3859 3
3860 1
3861 3
3862 0
3863 1
3864 2
3865 2
3866 1
3867 2
3868 2
3869 2
3870 0
3871 0
3872 2
3873 0
3874 0
3875 1
3876 1
3877 2
3878 0
3879 1
3880 2
3881 0
3882 3

# generate inverse attack

In [1]:
import copy
import numpy as np
def get_attack_list(graph_num,frame_num):
    attack_list = []
#     transition_matrix_list = [[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2],[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2]]
    transition_matrix_list = [[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35],[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35]]
    for frame in range(frame_num):
        attack_list_frame = []
        for group in range(graph_num):
            attack_list_frame.append(1)
        attack_list.append(attack_list_frame)
    p_q = [0.25,0.25,0.25,0.25]    
    
    cut_frame = int(frame_num/2)-1000
    for frame in range(cut_frame):
        if frame == 0:
            p0 = np.array(p_q)
        else : 
            p0 = np.array(transition_matrix_list[index])
        index = np.random.choice([0,1,2,3], p = p0.ravel())
        print(frame,index)
        attack_list_copy = copy.copy(attack_list)
        attack_list_copy[frame][index] = 0
    
#     transition_matrix_list = [[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35],[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35]]
    transition_matrix_list = [[0.35,0.15,0.45,0.05],[0.3,0.2,0.4,0.1],[0.35,0.15,0.45,0.05],[0.3,0.2,0.4,0.1]]
    cut_frame_inverse = frame_num - cut_frame
    for frame in range(cut_frame_inverse):
        frame = frame+ 2000
        p0 = np.array(transition_matrix_list[index])
        index = np.random.choice([0,1,2,3], p = p0.ravel())
        print(frame,index)
        attack_list_copy = copy.copy(attack_list)
        attack_list_copy[frame][index] = 0
    
    return attack_list_copy

attack_list_copy = get_attack_list(4,6000)
# print(attack_list)
filename = 'markov_attack_list_0713_2022_4T.txt'
np.savetxt(filename,attack_list_copy)
print(attack_list_copy)

0 3
1 2
2 3
3 3
4 1
5 1
6 1
7 1
8 1
9 3
10 0
11 1
12 1
13 3
14 1
15 0
16 1
17 3
18 3
19 3
20 3
21 3
22 3
23 1
24 2
25 3
26 3
27 1
28 2
29 3
30 3
31 0
32 2
33 2
34 2
35 0
36 2
37 1
38 3
39 0
40 1
41 0
42 2
43 1
44 3
45 3
46 3
47 1
48 1
49 1
50 0
51 3
52 1
53 3
54 1
55 2
56 3
57 1
58 2
59 3
60 3
61 1
62 0
63 3
64 0
65 2
66 2
67 1
68 3
69 0
70 3
71 1
72 3
73 3
74 3
75 3
76 1
77 3
78 3
79 0
80 3
81 1
82 3
83 2
84 3
85 1
86 1
87 1
88 3
89 1
90 1
91 0
92 2
93 1
94 1
95 2
96 2
97 1
98 2
99 0
100 0
101 2
102 0
103 0
104 3
105 1
106 3
107 3
108 3
109 3
110 1
111 1
112 1
113 0
114 2
115 0
116 3
117 3
118 1
119 1
120 3
121 0
122 0
123 0
124 1
125 0
126 1
127 0
128 2
129 0
130 2
131 3
132 1
133 0
134 3
135 1
136 1
137 1
138 0
139 2
140 3
141 3
142 1
143 1
144 2
145 2
146 3
147 1
148 3
149 3
150 3
151 3
152 2
153 1
154 0
155 1
156 0
157 1
158 0
159 2
160 0
161 1
162 2
163 3
164 2
165 3
166 0
167 1
168 0
169 1
170 3
171 0
172 2
173 1
174 1
175 1
176 1
177 1
178 1
179 0
180 3
181 1
182 3
183 1
184 1


1718 1
1719 0
1720 1
1721 0
1722 2
1723 0
1724 1
1725 1
1726 0
1727 2
1728 1
1729 3
1730 0
1731 2
1732 1
1733 3
1734 0
1735 3
1736 1
1737 3
1738 1
1739 3
1740 1
1741 2
1742 1
1743 1
1744 1
1745 1
1746 1
1747 1
1748 1
1749 0
1750 1
1751 3
1752 3
1753 3
1754 1
1755 1
1756 0
1757 0
1758 2
1759 1
1760 3
1761 0
1762 2
1763 3
1764 1
1765 3
1766 1
1767 1
1768 1
1769 3
1770 1
1771 2
1772 3
1773 1
1774 2
1775 3
1776 1
1777 1
1778 3
1779 2
1780 0
1781 3
1782 3
1783 2
1784 2
1785 3
1786 1
1787 3
1788 2
1789 2
1790 2
1791 3
1792 3
1793 0
1794 3
1795 1
1796 2
1797 3
1798 1
1799 1
1800 3
1801 0
1802 3
1803 3
1804 1
1805 1
1806 1
1807 0
1808 3
1809 1
1810 2
1811 0
1812 1
1813 1
1814 0
1815 0
1816 1
1817 1
1818 1
1819 0
1820 0
1821 0
1822 2
1823 3
1824 1
1825 2
1826 3
1827 0
1828 0
1829 0
1830 1
1831 1
1832 3
1833 1
1834 3
1835 3
1836 2
1837 3
1838 0
1839 2
1840 1
1841 3
1842 0
1843 3
1844 0
1845 1
1846 2
1847 0
1848 1
1849 0
1850 1
1851 0
1852 0
1853 0
1854 3
1855 1
1856 3
1857 1
1858 2
1859 1
1860 3

3331 2
3332 1
3333 0
3334 0
3335 0
3336 2
3337 3
3338 0
3339 2
3340 0
3341 0
3342 2
3343 0
3344 2
3345 2
3346 2
3347 0
3348 2
3349 2
3350 3
3351 2
3352 0
3353 0
3354 2
3355 2
3356 2
3357 0
3358 1
3359 2
3360 2
3361 2
3362 0
3363 0
3364 2
3365 3
3366 0
3367 0
3368 2
3369 1
3370 2
3371 2
3372 2
3373 2
3374 2
3375 0
3376 0
3377 2
3378 0
3379 2
3380 2
3381 0
3382 1
3383 0
3384 2
3385 2
3386 1
3387 2
3388 2
3389 2
3390 0
3391 2
3392 1
3393 1
3394 3
3395 2
3396 1
3397 0
3398 2
3399 3
3400 1
3401 2
3402 2
3403 2
3404 2
3405 2
3406 0
3407 2
3408 0
3409 2
3410 1
3411 2
3412 2
3413 0
3414 2
3415 2
3416 0
3417 2
3418 0
3419 2
3420 2
3421 2
3422 2
3423 1
3424 0
3425 3
3426 0
3427 2
3428 2
3429 1
3430 0
3431 1
3432 2
3433 2
3434 2
3435 2
3436 1
3437 2
3438 3
3439 2
3440 1
3441 2
3442 0
3443 2
3444 3
3445 2
3446 2
3447 0
3448 1
3449 2
3450 2
3451 2
3452 0
3453 2
3454 0
3455 1
3456 0
3457 1
3458 0
3459 2
3460 0
3461 0
3462 1
3463 0
3464 0
3465 1
3466 0
3467 2
3468 1
3469 1
3470 0
3471 0
3472 3
3473 1

5005 2
5006 2
5007 0
5008 0
5009 1
5010 2
5011 0
5012 0
5013 2
5014 0
5015 0
5016 2
5017 2
5018 2
5019 0
5020 2
5021 1
5022 2
5023 2
5024 0
5025 0
5026 0
5027 2
5028 0
5029 2
5030 1
5031 2
5032 2
5033 2
5034 1
5035 1
5036 1
5037 0
5038 1
5039 2
5040 2
5041 0
5042 0
5043 2
5044 0
5045 2
5046 3
5047 1
5048 3
5049 2
5050 0
5051 0
5052 0
5053 0
5054 2
5055 2
5056 0
5057 1
5058 0
5059 0
5060 1
5061 1
5062 2
5063 2
5064 0
5065 2
5066 0
5067 2
5068 3
5069 2
5070 2
5071 2
5072 0
5073 0
5074 2
5075 2
5076 0
5077 2
5078 0
5079 2
5080 0
5081 0
5082 2
5083 2
5084 2
5085 2
5086 0
5087 2
5088 0
5089 2
5090 2
5091 0
5092 0
5093 0
5094 0
5095 0
5096 0
5097 0
5098 2
5099 2
5100 1
5101 0
5102 0
5103 2
5104 0
5105 0
5106 1
5107 2
5108 0
5109 1
5110 0
5111 2
5112 3
5113 2
5114 1
5115 2
5116 2
5117 0
5118 1
5119 3
5120 2
5121 1
5122 2
5123 2
5124 3
5125 2
5126 0
5127 2
5128 1
5129 2
5130 1
5131 1
5132 2
5133 2
5134 0
5135 3
5136 2
5137 1
5138 2
5139 0
5140 1
5141 2
5142 2
5143 1
5144 0
5145 2
5146 0
5147 0

In [6]:
frame_num = 8000
print(frame_num/2)

4000.0


In [2]:
filename = 'dataset/markov_attack_list_0713_2022_1.txt'
# filename = 'dataset/adaptive_attack_list_0713_2022_d1.txt'
import numpy as np
attack_list =  np.loadtxt(filename)
attack_list.tolist()
print(type(attack_list))
a0 = 0
a1 = 0
a2 = 0
a3 = 0
# attack_list[:,0].count(0)
for i in range(1000,1600):
    if attack_list[i][0] == 0:
        a0 = a0 + 1
    if attack_list[i][1] == 0:
        a1 = a1 +1
    if attack_list[i][2] == 0:
        a2 = a2 +1
    if attack_list[i][3] == 0:
        a3 = a3 +1
print(a0,a1,a2,a3)

<class 'numpy.ndarray'>
179 114 197 110


In [2]:
# filename = 'dataset/markov_attack_list_0713_2022_1T.txt'
attack_list =  np.loadtxt(filename)
attack_list.tolist()
print(type(attack_list))
a0 = 0
a1 = 0
a2 = 0
a3 = 0
# attack_list[:,0].count(0)
for i in range(6000):
    if attack_list[i][0] == 0:
        a0 = a0 + 1
    if attack_list[i][1] == 0:
        a1 = a1 +1
    if attack_list[i][2] == 0:
        a2 = a2 +1
    if attack_list[i][3] == 0:
        a3 = a3 +1
print(a0,a1,a2,a3)

<class 'numpy.ndarray'>
1700 1289 2085 926


In [6]:
import numpy as np
filename = 'dataset/markov_attack_list_0713_2022_1.txt'
attack_list =  np.loadtxt(filename)
attack_list.tolist()
attack_cut1_3 = attack_list[0:3000]
print(attack_cut1_3)
filename = 'markov_attack_list_0713_2022_1_cut13.txt'
np.savetxt(filename,attack_cut1_3)

[[0. 1. 1. 1.]
 [0. 1. 1. 1.]
 [1. 1. 1. 0.]
 ...
 [0. 1. 1. 1.]
 [1. 1. 0. 1.]
 [0. 1. 1. 1.]]


In [4]:
a0 = 0
a1 = 0
a2 = 0
a3 = 0
# attack_list[:,0].count(0)
for i in range(3000):
    if attack_list[i][0] == 0:
        a0 = a0 + 1
    if attack_list[i][1] == 0:
        a1 = a1 +1
    if attack_list[i][2] == 0:
        a2 = a2 +1
    if attack_list[i][3] == 0:
        a3 = a3 +1
print(a0,a1,a2,a3)

1029 494 960 517
